version: 2

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: examples/
      linters:
        - errcheck
        - unused

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
